__title__ = 'STAplus API Python Client'
__version__ = '0.1'
__license__ = 'LGPL3'
__author__ = 'Andreas Matheus'
__copyright__ = 'Secure Dimensions'
__contact__ = 'am@secure-dimensions.de'
__url__ = 'https://github.com/securedimensions/FROST-Python-Client'
__description__ = 'a client library to facilitate interaction with a STAplus SensorThingsAPI Server'
