__title__ = 'STAplus Python Client'
__version__ = '0.8'
__license__ = 'LGPL3'
__author__ = 'Andreas Matheus'
__copyright__ = 'Secure Dimensions'
__contact__ = 'am@secure-dimensions.de'
__url__ = 'https://github.com/securedimensions/STAplus-Python-Client'
__description__ = 'A client library to facilitate interaction with a STAplus SensorThings API Server'
